### ISSUE TITLE
Ook?

### ISSUE THREAD

**Issue by Haroenv** [bullgit/blah-code-cli#3]
Ook? Ook Ook!?. Ook? Ook? Ook?. Ook? Ook? Oook!?. Ook?! Ook!. Ook? Ook Ook. Ook? Ook? Ook?. Ook?! Ook!. Oook! Ook?!. Ook?! Ook!. Ook? Ook? Oook!. Ook? Ook? Oook. Ook? Ook Ook?. Ook?! Ook!. Oook! Oook!?. Ook? Ook? Ook?. Ook? Ook Oook!. Ook?! Ook!. Ook? Ook Oook. Ook? Ook? Ook. Ook?! Ook!. Ook? Ook? Oook?. Ook? Ook Ook!?. Ook? Ook Ook?. Ook?! Ook!. Ook? Ook? Oook?. Ook? Ook Ook?. Ook? Ook? Ook!?. Ook? Ook Oook!?. Ook? Ook Oook. Ook? Ook? Ook. Oook!? Oook!. Ook? Ook Oook?!. Oook? Ook?!. Oook? Ook?!. Oook? Ook?!. Ook?! Ook!. Oook Oook Ook?! Oook Oook!. Oook Oook? Oook!? Ook Oook?

**Comment by mischah** [comment]
haha. Taking care of it after publishing the API in V2 to npm 🐒

**Comment by mischah** [comment]
mhm. Or should I first update the gh pages demo with an ape/blah code radio button?

**Comment by Haroenv** [comment]
Site first imo, faster too
